"""Refactor: extract duplicate code blocks into helper functions using an LLM."""

from __future__ import annotations
from .collectors import _FunctionCollector  # fmt: skip # noqa: F401, E501
from .collectors import _FunctionInfo  # fmt: skip # noqa: F401, E501
from .collectors import _SeqInfo  # fmt: skip # noqa: F401, E501
from .collectors import _SequenceCollector  # fmt: skip # noqa: F401, E501
from .collectors import _build_function_body_fps  # fmt: skip # noqa: F401, E501
from .collectors import _collect_called_names  # fmt: skip # noqa: F401, E501
from .collectors import _filter_maximal_groups  # fmt: skip # noqa: F401, E501
from .collectors import _find_duplicate_groups  # fmt: skip # noqa: F401, E501
from .collectors import _has_internal_overlap  # fmt: skip # noqa: F401, E501
from .collectors import _overlaps_diff  # fmt: skip # noqa: F401, E501
from .collectors import _seq_source_contains_yield  # fmt: skip # noqa: F401, E501
from .llm_integration import _generate_no_arg_call  # fmt: skip # noqa: F401, E501
from .llm_integration import _llm_extract  # fmt: skip # noqa: F401, E501
from .llm_integration import _llm_generate_call  # fmt: skip # noqa: F401, E501
from .llm_integration import _llm_verify_extraction  # fmt: skip # noqa: F401, E501
from .llm_integration import _llm_veto  # fmt: skip # noqa: F401, E501
from .llm_integration import _llm_veto_func_match  # fmt: skip # noqa: F401, E501
from .text_editing import _apply_edits  # fmt: skip # noqa: F401, E501
from .text_editing import _build_helper_insertion  # fmt: skip # noqa: F401, E501
from .text_editing import _find_insertion_point  # fmt: skip # noqa: F401, E501
from .text_editing import _skip_class_docstring  # fmt: skip # noqa: F401, E501
from .utils import _ApiTimeout  # fmt: skip # noqa: F401, E501
from .utils import _has_def  # fmt: skip # noqa: F401, E501
from .utils import _node_weight  # fmt: skip # noqa: F401, E501
from .utils import _normalize_source  # fmt: skip # noqa: F401, E501
from .utils import _run_with_timeout  # fmt: skip # noqa: F401, E501
from .utils import _sequence_weight  # fmt: skip # noqa: F401, E501
from .utils import _strip_helper_docstring  # fmt: skip # noqa: F401, E501
from .verification import _collect_ast_store_names  # fmt: skip # noqa: F401, E501
from .verification import _collect_attribute_names  # fmt: skip # noqa: F401, E501
from .verification import _collect_called_attr_names  # fmt: skip # noqa: F401, E501
from .verification import _extract_defined_names  # fmt: skip # noqa: F401, E501
from .verification import _find_escaping_vars  # fmt: skip # noqa: F401, E501
from .verification import _has_call_to  # fmt: skip # noqa: F401, E501
from .verification import _has_funcdef  # fmt: skip # noqa: F401, E501
from .verification import _has_mutable_literal_is_check  # fmt: skip # noqa: F401, E501
from .verification import _has_param_overwritten_before_read  # fmt: skip # noqa: F401, E501
from .verification import _helper_imports_local_name  # fmt: skip # noqa: F401, E501
from .verification import _is_pure_literal  # fmt: skip # noqa: F401, E501
from .verification import _lift_and_dedup_imports  # fmt: skip # noqa: F401, E501
from .verification import _missing_free_vars  # fmt: skip # noqa: F401, E501
from .verification import _names_assigned_in  # fmt: skip # noqa: F401, E501
from .verification import _names_in_edit_texts  # fmt: skip # noqa: F401, E501
from .verification import _normalize_replacement_indentation  # fmt: skip # noqa: F401, E501
from .verification import _pyflakes_new_undefined_names  # fmt: skip # noqa: F401, E501
from .verification import _pyflakes_strip_unused_simple_assigns  # fmt: skip # noqa: F401, E501
from .verification import _replace_unused_in_target  # fmt: skip # noqa: F401, E501
from .verification import _replacement_contains_return  # fmt: skip # noqa: F401, E501
from .verification import _replacement_steals_post_block_line  # fmt: skip # noqa: F401, E501
from .verification import _scope_end_line  # fmt: skip # noqa: F401, E501
from .verification import _seq_ends_with_return  # fmt: skip # noqa: F401, E501
from .verification import _strip_unused_call_assignments  # fmt: skip # noqa: F401, E501
from .verification import _verify_extraction  # fmt: skip # noqa: F401, E501
from .verification import _would_create_proxy_wrappers  # fmt: skip # noqa: F401, E501
from .extractor import DuplicateExtractor  # fmt: skip # noqa: F401, E501
