from __future__ import annotations
from .ast_analysis_utils import _collect_ast_store_names  # fmt: skip # noqa: F401, E501
from .ast_analysis_utils import _collect_attribute_names  # fmt: skip # noqa: F401, E501
from .ast_analysis_utils import _collect_called_attr_names  # fmt: skip # noqa: F401, E501
from .ast_analysis_utils import _extract_defined_names  # fmt: skip # noqa: F401, E501
from .ast_analysis_utils import _find_escaping_vars  # fmt: skip # noqa: F401, E501
from .ast_analysis_utils import _is_pure_literal  # fmt: skip # noqa: F401, E501
from .ast_analysis_utils import _names_assigned_in  # fmt: skip # noqa: F401, E501
from .ast_analysis_utils import _names_in_edit_texts  # fmt: skip # noqa: F401, E501
from .editing_and_insertion import _apply_edits  # fmt: skip # noqa: F401, E501
from .editing_and_insertion import _build_helper_insertion  # fmt: skip # noqa: F401, E501
from .editing_and_insertion import _find_insertion_point  # fmt: skip # noqa: F401, E501
from .editing_and_insertion import _lift_and_dedup_imports  # fmt: skip # noqa: F401, E501
from .editing_and_insertion import _normalize_replacement_indentation  # fmt: skip # noqa: F401, E501
from .editing_and_insertion import _replace_unused_in_target  # fmt: skip # noqa: F401, E501
from .editing_and_insertion import _scope_end_line  # fmt: skip # noqa: F401, E501
from .editing_and_insertion import _skip_class_docstring  # fmt: skip # noqa: F401, E501
from .editing_and_insertion import _strip_helper_docstring  # fmt: skip # noqa: F401, E501
from .editing_and_insertion import _strip_unused_call_assignments  # fmt: skip # noqa: F401, E501
from .verification import _has_call_to  # fmt: skip # noqa: F401, E501
from .verification import _has_funcdef  # fmt: skip # noqa: F401, E501
from .verification import _has_mutable_literal_is_check  # fmt: skip # noqa: F401, E501
from .verification import _has_param_overwritten_before_read  # fmt: skip # noqa: F401, E501
from .verification import _helper_imports_local_name  # fmt: skip # noqa: F401, E501
from .verification import _missing_free_vars  # fmt: skip # noqa: F401, E501
from .verification import _pyflakes_new_undefined_names  # fmt: skip # noqa: F401, E501
from .verification import _pyflakes_strip_unused_simple_assigns  # fmt: skip # noqa: F401, E501
from .verification import _replacement_contains_return  # fmt: skip # noqa: F401, E501
from .verification import _replacement_steals_post_block_line  # fmt: skip # noqa: F401, E501
from .verification import _seq_ends_with_return  # fmt: skip # noqa: F401, E501
from .verification import _verify_extraction  # fmt: skip # noqa: F401, E501
from .verification import _would_create_proxy_wrappers  # fmt: skip # noqa: F401, E501
